Branches_1: Branches_1.asm
	nasm -f elf -g -F dwarf Branches_1.asm
	ld -m elf_i386 -o Branches1 Branches_1.o


Branches_2: Branches_2.asm
	nasm -f elf -g -F dwarf Branches_2.asm
	ld -m elf_i386 -o Branches2 Branches_2.o


